### ISSUE TITLE
core-transition throwing exception

### ISSUE THREAD

**Issue by npezza93** [ahuth/emcee#39]
When using anything that extends core-transition(core-overlay,paper-dialog,dropdowns,  etc.) Firefox throws an exception and either renders a blank page or does not render the tag:

 `"Exception caught during observer callback: styles.installScopeStyle@https://cal-class-schedule-npezza.c9.io/assets/polymer/polymer.html?body=1.js:10189:11
.setup@https://cal-class-schedule-npezza.c9.io/assets/core-transition/core-transition-css.html?body=1.js:73:1
.ensureTargetSetup@https://cal-class-schedule-npezza.c9.io/assets/core-overlay/core-overlay.html?body=1.js:228:9
.openedChanged@https://cal-class-schedule-npezza.c9.io/assets/core-overlay/core-overlay.html?body=1.js:241:7
properties.invokeMethod@https://cal-class-schedule-npezza.c9.io/assets/polymer/polymer.html?body=1.js:9383:9
properties.notifyPropertyChanges@https://cal-class-schedule-npezza.c9.io/assets/polymer/polymer.html?body=1.js:9372:15
Observer.prototype.report_@https://cal-class-schedule-npezza.c9.io/assets/polymer/polymer.html?body=1.js:4912:9
CompoundObserver.prototype<.check_@https://cal-class-schedule-npezza.c9.io/assets/polymer/polymer.html?body=1.js:5318:1
global.Platform.performMicrotaskCheckpoint@https://cal-class-schedule-npezza.c9.io/assets/polymer/polymer.html?body=1.js:4973:13
flush/<@https://cal-class-schedule-npezza.c9.io/assets/polymer/polymer.html?body=1.js:8176:7
atEndOfMicrotask@https://cal-class-schedule-npezza.c9.io/assets/polymer/polymer.html?body=1.js:8121:5
notifyObservers@https://cal-class-schedule-npezza.c9.io/assets/webcomponentsjs/webcomponents.js?body=1:577:13
handle@https://cal-class-schedule-npezza.c9.io/assets/webcomponentsjs/webcomponents.js?body=1:522:1
"`

Has anyone experienced this issue or know how to fix it.

**Comment by ahuth** [comment]
Thanks for bringing up this issue! Unfortunately, I'm not maintaining this project anymore (although I will look at pull requests).
